language: node_js
node_js:
- node
before_deploy:
  - rm .gitignore
  - npm run build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $S3_BUCKET
  local_dir: dist
  upload-dir: $S3_UPLOAD_DIR
  skip_cleanup: true
  on:
    branch: master
notifications:
  email:
    on_success: change
    on_failure: always
